### ISSUE TITLE
Issue with Queue

### ISSUE THREAD

**Issue by Entelogical** [denispionicul/Stardust#1]
Queue currently does not allow a normal function to be passed into it - instead it is expecting a Promise. The documentation does not properly demo this behavior

**Comment by denispionicul** [comment]
Sorry for not seeing this earlier, I will rework the module as soon as possible. Thank you for the notice

**Comment by denispionicul** [comment]
Switched from promises to a simple repeat loop, everything should be working fine now. Thanks again
