### ISSUE TITLE
Revise `SetState` on Stater to Ensure `State` is Updated Before Invoking

### ISSUE THREAD

**Issue by KhanPython** [denispionicul/Stardust#3]
The current implementation of the `SetState` function in Stater system fires observer notifications before updating the state internally. This may lead to inconsistencies and race conditions, e.g observers react to a state change that has not yet been fully applied. 

```lua
data.Stater.Changed:Connect(function(currentState)
    warn(currentState, data.Stater:GetCurrentState())
    -- output: "X", "Y"
end)
```

**Comment by denispionicul** [comment]
Fixed in 1.0.2! Thank you for the notice.
